import json
import os

def main():
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Pemetaan Kualitas Air Pesisir Provinsi Banten Per Kecamatan\n",
                "### Analisis Spasial Komparatif Berbasis openEO & Sentinel-2\n",
                "\n",
                "Notebook ini digunakan untuk menganalisis kualitas air pesisir per kecamatan di Banten (2017 vs 2026) menggunakan citra Sentinel-2. Parameter kualitas air yang dideteksi:\n",
                "1. **Kekeruhan (NDTI - Turbidity)**: Kriteria sedimentasi pantai.\n",
                "2. **Klorofil-a (NDCI - Chlorophyll-a)**: Kriteria nutrien/blooming alga.\n",
                "3. **TSS (Total Suspended Solids) & CDOM**: Indikator material tersuspensi dan materi organik terlarut.\n",
                "4. **Model Klasifikasi Supervised**: Random Forest Classifier dilatih secara global untuk Banten untuk mengklasifikasi status kualitas air (**SEHAT**, **SEDANG**, **TIDAK SEHAT**)."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 1. Setup Lingkungan & Import Library"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Install dependensi eksternal (jalankan jika belum terinstal pada environment saat ini)\n",
                "# !pip install openeo rasterio rioxarray xarray geopandas shapely fiona folium scikit-learn matplotlib pandas numpy joblib\n",
                "\n",
                "import os\n",
                "import sys\n",
                "import glob\n",
                "import shutil\n",
                "import tempfile\n",
                "import time\n",
                "import json\n",
                "import joblib\n",
                "from datetime import datetime\n",
                "\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import xarray as xr\n",
                "import geopandas as gpd\n",
                "import rioxarray\n",
                "import folium\n",
                "from folium import plugins\n",
                "from shapely.geometry import mapping\n",
                "from sklearn.ensemble import RandomForestClassifier\n",
                "\n",
                "print(\"Libraries successfully imported.\")\n",
                "print(f\"Execution timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 2. Koneksi dan Autentikasi openEO"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "print(\"Connecting to Copernicus Data Space Ecosystem (openEO)...\")\n",
                "try:\n",
                "    import openeo\n",
                "    connection = openeo.connect('https://openeo.dataspace.copernicus.eu')\n",
                "    connection.authenticate_oidc()\n",
                "    print(\"Authentication successful. openEO session initialized.\")\n",
                "except Exception as e:\n",
                "    print(f\"Warning: openEO connection failed ({e}). Kelanjutan unduhan openEO mungkin terganggu.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 3. Konfigurasi Parameter Kualitas Air"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Parameter Temporal\n",
                "YEAR_T1 = 2017          # Tahun dasar (baseline)\n",
                "YEAR_T2 = 2026          # Tahun pembanding (terkini)\n",
                "\n",
                "# Parameter Musiman (target musim kemarau untuk reduksi tutupan awan)\n",
                "DRY_SEASON_START = 5    # Mei\n",
                "DRY_SEASON_END = 10     # Oktober\n",
                "\n",
                "SCALE_EXPORT = 30       # Resolusi ekspor composite (30 meter)\n",
                "GADM_PATH = \"data/gadm41_IDN.gpkg\"\n",
                "COMPOSITE_DIR = \"data/composites\"\n",
                "OUTPUT_DIR = \"output\"\n",
                "\n",
                "# Batas Klasifikasi Kualitas Air (Threshold Fisik-Kimiawi)\n",
                "NDTI_TURBID_THRESHOLD = 0.05       # NDTI > 0.05 -> Sangat Keruh (Tidak Sehat)\n",
                "NDCI_BLOOM_THRESHOLD = 0.08        # NDCI > 0.08 -> Blooming Alga (Tidak Sehat)\n",
                "NDCI_LOW_THRESHOLD = -0.02         # NDCI <= -0.02 -> Sangat Jernih/Rendah Nutrisi\n",
                "NDTI_CLEAR_THRESHOLD = -0.05       # NDTI <= -0.05 -> Sangat Jernih\n",
                "\n",
                "print(\"Configuration parameters successfully loaded.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 4. Ekstraksi Wilayah Kecamatan Pesisir Banten (Batas Laut 3 km)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def load_banten_coastal_kecamatans(gadm_path=GADM_PATH, buffer_meters=3000, min_water_area_ha=10.0):\n",
                "    print(\"Mengekstrak data batas wilayah kecamatan pesisir Banten...\")\n",
                "    if not os.path.exists(gadm_path):\n",
                "        raise FileNotFoundError(f\"File GADM tidak ditemukan di {gadm_path}. Silakan jalankan data_downloader.py terlebih dahulu.\")\n",
                "        \n",
                "    gdf = gpd.read_file(gadm_path, layer=\"ADM_ADM_3\")\n",
                "    \n",
                "    # Saring Banten dan tetangganya\n",
                "    banten = gdf[gdf[\"NAME_1\"] == \"Banten\"].copy()\n",
                "    neighbors = gdf[gdf[\"NAME_1\"].isin([\"Banten\", \"Jawa Barat\", \"Jakarta Raya\", \"Dki Jakarta\"])].copy()\n",
                "    \n",
                "    # Proyeksikan ke UTM 48S (EPSG:32748) untuk operasi buffer dalam meter\n",
                "    banten_utm = banten.to_crs(epsg=32748)\n",
                "    neighbors_utm = neighbors.to_crs(epsg=32748)\n",
                "    land_geom = neighbors_utm.union_all()\n",
                "    \n",
                "    coastal_rows = []\n",
                "    for idx, row in banten_utm.iterrows():\n",
                "        geom = row.geometry\n",
                "        name_3 = row[\"NAME_3\"]\n",
                "        name_2 = row[\"NAME_2\"]\n",
                "        gid_3 = row[\"GID_3\"]\n",
                "        \n",
                "        # Buat buffer 3 km\n",
                "        buffered = geom.buffer(buffer_meters)\n",
                "        \n",
                "        # Kurangkan daratan untuk mendapatkan zona perairan pesisir\n",
                "        water_zone = buffered.difference(land_geom)\n",
                "        water_area_ha = water_zone.area / 10000.0\n",
                "        \n",
                "        if water_area_ha >= min_water_area_ha:\n",
                "            coastal_rows.append({\n",
                "                \"GID_3\": gid_3,\n",
                "                \"Kabupaten_Kota\": name_2,\n",
                "                \"Kecamatan\": name_3,\n",
                "                \"water_area_ha\": water_area_ha,\n",
                "                \"land_geom\": geom,\n",
                "                \"geometry\": water_zone\n",
                "            })\n",
                "            \n",
                "    coastal_gdf = gpd.GeoDataFrame(coastal_rows, crs=\"EPSG:32748\")\n",
                "    coastal_gdf = coastal_gdf.to_crs(epsg=4326)\n",
                "    coastal_gdf[\"land_geom\"] = coastal_gdf[\"land_geom\"].apply(lambda g: gpd.GeoSeries([g], crs=\"EPSG:32748\").to_crs(epsg=4326).iloc[0])\n",
                "    \n",
                "    print(f\"Ditemukan {len(coastal_gdf)} kecamatan pesisir di Banten.\")\n",
                "    return coastal_gdf\n",
                "\n",
                "coastal_gdf = load_banten_coastal_kecamatans()\n",
                "coastal_gdf[[\"Kabupaten_Kota\", \"Kecamatan\", \"water_area_ha\"]].head(10)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 5. Fungsi openEO Composite Downloader & Indeks Spektral Kualitas Air"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def get_sentinel2_water_composite_job(connection, bbox, year, scale_export=SCALE_EXPORT):\n",
                "    start_date = f\"{year}-{DRY_SEASON_START:02d}-01\"\n",
                "    end_date   = f\"{year}-{DRY_SEASON_END:02d}-31\"\n",
                "\n",
                "    extent = {\n",
                "        \"west\": bbox[0], \"south\": bbox[1],\n",
                "        \"east\": bbox[2], \"north\": bbox[3],\n",
                "        \"crs\": \"EPSG:4326\",\n",
                "    }\n",
                "\n",
                "    cube = connection.load_collection(\n",
                "        \"SENTINEL2_L2A\",\n",
                "        spatial_extent=extent,\n",
                "        temporal_extent=[start_date, end_date],\n",
                "        bands=[\"B02\", \"B03\", \"B04\", \"B05\", \"B08\", \"B11\", \"SCL\"],\n",
                "    )\n",
                "\n",
                "    scl = cube.band(\"SCL\")\n",
                "    cloud_mask = ~(\n",
                "        (scl == 1) | (scl == 3) | (scl == 8) |\n",
                "        (scl == 9) | (scl == 10) | (scl == 11)\n",
                "    )\n",
                "    masked_cube = cube.mask(cloud_mask)\n",
                "\n",
                "    res_deg = scale_export / 111320.0\n",
                "    resampled = masked_cube.resample_spatial(\n",
                "        resolution=res_deg, projection=4326, method=\"bilinear\",\n",
                "    )\n",
                "    composite = resampled.reduce_dimension(reducer=\"median\", dimension=\"t\")\n",
                "    return composite.filter_bands([\"B02\", \"B03\", \"B04\", \"B05\", \"B08\", \"B11\"])\n",
                "\n",
                "def download_banten_composite(connection, bbox, year, output_path, scale_export=SCALE_EXPORT):\n",
                "    if os.path.exists(output_path):\n",
                "        print(f\"Composite untuk tahun {year} sudah tersedia di: {output_path}\")\n",
                "        return\n",
                "    print(f\"Mengajukan batch job openEO untuk composite Banten tahun {year}...\")\n",
                "    cube = get_sentinel2_water_composite_job(connection, bbox, year, scale_export)\n",
                "    cube = cube.save_result(\"GTiff\")\n",
                "\n",
                "    job = cube.create_job(title=f\"banten_water_quality_{year}\")\n",
                "    job.start_and_wait()\n",
                "\n",
                "    os.makedirs(os.path.dirname(output_path), exist_ok=True)\n",
                "    with tempfile.TemporaryDirectory() as tmpdir:\n",
                "        job.download_results(tmpdir)\n",
                "        downloaded = glob.glob(os.path.join(tmpdir, \"*.tif\"))\n",
                "        if downloaded:\n",
                "            shutil.move(downloaded[0], output_path)\n",
                "            print(f\"Composite berhasil disimpan ke: {output_path}\")\n",
                "        else:\n",
                "            raise RuntimeError(\"Gagal mengunduh file dari openEO.\")\n",
                "\n",
                "def load_composite_as_dataset(tif_path):\n",
                "    raw = rioxarray.open_rasterio(tif_path)\n",
                "    filename = os.path.basename(tif_path)\n",
                "    if \"Water\" in filename:\n",
                "        band_names = [\"B02\", \"B03\", \"B04\", \"B05\", \"B08\", \"B11\"]\n",
                "        print(f\"Memuat composite dengan B05 (Red Edge): {filename}\")\n",
                "    else:\n",
                "        band_names = [\"B02\", \"B03\", \"B04\", \"B08\", \"B11\", \"B12\"]\n",
                "        print(f\"Memuat composite standar (menggunakan fallback): {filename}\")\n",
                "        \n",
                "    ds = xr.Dataset({\n",
                "        name: raw.sel(band=i + 1).drop_vars(\"band\")\n",
                "        for i, name in enumerate(band_names)\n",
                "    })\n",
                "    ds = ds.rio.write_crs(\"EPSG:4326\")\n",
                "    return ds\n",
                "\n",
                "def calculate_water_quality_indices(ds):\n",
                "    blue  = ds[\"B02\"]\n",
                "    green = ds[\"B03\"]\n",
                "    red   = ds[\"B04\"]\n",
                "    eps   = 1e-10\n",
                "\n",
                "    if \"B11\" in ds:\n",
                "        swir1 = ds[\"B11\"]\n",
                "        ds[\"MNDWI\"] = (green - swir1) / (green + swir1 + eps)\n",
                "    else:\n",
                "        nir = ds[\"B08\"]\n",
                "        ds[\"MNDWI\"] = (green - nir) / (green + nir + eps)\n",
                "\n",
                "    ds[\"NDTI\"] = (green - red) / (green + red + eps)\n",
                "\n",
                "    if \"B05\" in ds:\n",
                "        red_edge = ds[\"B05\"]\n",
                "        ds[\"NDCI\"] = (red_edge - red) / (red_edge + red + eps)\n",
                "    else:\n",
                "        ds[\"NDCI\"] = (green - blue) / (green + blue + eps)\n",
                "\n",
                "    ds[\"TSS\"] = red / (green + eps)\n",
                "    ds[\"CDOM\"] = green / (blue + eps)\n",
                "    return ds"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 6. Algoritma Klasifikasi Kualitas Air & Analisis Lokal"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def classify_water_pixels_threshold(ds):\n",
                "    mndwi = ds[\"MNDWI\"].values\n",
                "    ndti  = ds[\"NDTI\"].values\n",
                "    ndci  = ds[\"NDCI\"].values\n",
                "    \n",
                "    water_mask = (mndwi > 0.0) & (~np.isnan(mndwi))\n",
                "    classes = np.zeros_like(mndwi, dtype=np.uint8)\n",
                "    \n",
                "    # 1. Kekeruhan Tinggi\n",
                "    turbid_mask = water_mask & (ndti > NDTI_TURBID_THRESHOLD)\n",
                "    classes[turbid_mask] = 1\n",
                "    \n",
                "    # 2. Blooming Alga\n",
                "    bloom_mask = water_mask & (ndci > NDCI_BLOOM_THRESHOLD) & (classes == 0)\n",
                "    classes[bloom_mask] = 2\n",
                "    \n",
                "    # 3. Rendah Nutrisi\n",
                "    clear_low_nut_mask = water_mask & (ndci <= NDCI_LOW_THRESHOLD) & (ndti <= NDTI_CLEAR_THRESHOLD) & (classes == 0)\n",
                "    classes[clear_low_nut_mask] = 3\n",
                "    \n",
                "    # 4. Kondisi Optimum (Sehat)\n",
                "    optimum_mask = (\n",
                "        water_mask & \n",
                "        (ndti > NDTI_CLEAR_THRESHOLD) & (ndti <= NDTI_TURBID_THRESHOLD) &\n",
                "        (ndci > NDCI_LOW_THRESHOLD) & (ndci <= NDCI_BLOOM_THRESHOLD) &\n",
                "        (classes == 0)\n",
                "    )\n",
                "    classes[optimum_mask] = 4\n",
                "    \n",
                "    # 5. Kondisi Sedang / Lainnya\n",
                "    sedang_mask = water_mask & (classes == 0)\n",
                "    classes[sedang_mask] = 5\n",
                "    return classes\n",
                "\n",
                "def train_water_quality_rf(ds, threshold_classes):\n",
                "    water_mask = threshold_classes > 0\n",
                "    features_bands = [\"NDVI\" if \"NDVI\" in ds else \"B08\", \"B02\", \"B03\", \"B04\", \"NDTI\", \"NDCI\", \"TSS\", \"CDOM\"]\n",
                "    features_bands = [f for f in features_bands if f in ds]\n",
                "    \n",
                "    features_list = [ds[band].values[water_mask] for band in features_bands]\n",
                "    X = np.stack(features_list, axis=1)\n",
                "    y = threshold_classes[water_mask]\n",
                "    \n",
                "    valid = ~np.isnan(X).any(axis=1)\n",
                "    X = X[valid]\n",
                "    y = y[valid]\n",
                "    \n",
                "    if len(X) < 100:\n",
                "        return None\n",
                "        \n",
                "    rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=5, random_state=42)\n",
                "    rf.fit(X, y)\n",
                "    \n",
                "    all_features = [ds[band].values for band in features_bands]\n",
                "    stacked = np.stack(all_features, axis=-1)\n",
                "    y_dim, x_dim, n_feats = stacked.shape\n",
                "    flat_all = stacked.reshape(-1, n_feats)\n",
                "    flat_water_mask = water_mask.reshape(-1)\n",
                "    valid_flat = flat_water_mask & (~np.isnan(flat_all).any(axis=1))\n",
                "    \n",
                "    predicted_flat = np.zeros(y_dim * x_dim, dtype=np.uint8)\n",
                "    if np.sum(valid_flat) > 0:\n",
                "        predicted_flat[valid_flat] = rf.predict(flat_all[valid_flat])\n",
                "        \n",
                "    return predicted_flat.reshape(y_dim, x_dim)\n",
                "\n",
                "def compute_pixel_area_ha(ds):\n",
                "    res_x = abs(ds.rio.transform()[0])\n",
                "    res_y = abs(ds.rio.transform()[4])\n",
                "    return (res_x * 111320.0) * (res_y * 111320.0) / 10000.0\n",
                "\n",
                "def analyze_kecamatan_water_quality(ds, geom, pixel_area_ha):\n",
                "    try:\n",
                "        clipped_ds = ds.rio.clip([geom], crs=\"EPSG:4326\", all_touched=True)\n",
                "    except Exception as e:\n",
                "        return None\n",
                "        \n",
                "    clipped_ds = calculate_water_quality_indices(clipped_ds)\n",
                "    threshold_classes = classify_water_pixels_threshold(clipped_ds)\n",
                "    final_classes = train_water_quality_rf(clipped_ds, threshold_classes)\n",
                "    if final_classes is None:\n",
                "        final_classes = threshold_classes\n",
                "        \n",
                "    total_water_pixels = np.sum(final_classes > 0)\n",
                "    if total_water_pixels == 0:\n",
                "        return None\n",
                "        \n",
                "    unhealthy_pixels = np.sum((final_classes == 1) | (final_classes == 2))\n",
                "    healthy_pixels = np.sum(final_classes == 4)\n",
                "    moderate_pixels = np.sum((final_classes == 3) | (final_classes == 5))\n",
                "    \n",
                "    water_area_ha = float(total_water_pixels * pixel_area_ha)\n",
                "    healthy_ha = float(healthy_pixels * pixel_area_ha)\n",
                "    moderate_ha = float(moderate_pixels * pixel_area_ha)\n",
                "    unhealthy_ha = float(unhealthy_pixels * pixel_area_ha)\n",
                "    \n",
                "    pct_healthy = (healthy_ha / water_area_ha * 100) if water_area_ha > 0 else 0\n",
                "    pct_moderate = (moderate_ha / water_area_ha * 100) if water_area_ha > 0 else 0\n",
                "    pct_unhealthy = (unhealthy_ha / water_area_ha * 100) if water_area_ha > 0 else 0\n",
                "    \n",
                "    water_mask = final_classes > 0\n",
                "    mean_ndti = float(np.nanmean(clipped_ds[\"NDTI\"].values[water_mask]))\n",
                "    mean_ndci = float(np.nanmean(clipped_ds[\"NDCI\"].values[water_mask]))\n",
                "    mean_tss = float(np.nanmean(clipped_ds[\"TSS\"].values[water_mask]))\n",
                "    mean_cdom = float(np.nanmean(clipped_ds[\"CDOM\"].values[water_mask]))\n",
                "    \n",
                "    if pct_healthy > 50.0:\n",
                "        status = \"SEHAT\"\n",
                "    elif pct_unhealthy > 30.0:\n",
                "        status = \"TIDAK SEHAT\"\n",
                "    else:\n",
                "        status = \"SEDANG\"\n",
                "        \n",
                "    return {\n",
                "        \"water_area_ha\": round(water_area_ha, 2),\n",
                "        \"healthy_ha\": round(healthy_ha, 2),\n",
                "        \"moderate_ha\": round(moderate_ha, 2),\n",
                "        \"unhealthy_ha\": round(unhealthy_ha, 2),\n",
                "        \"pct_healthy\": round(pct_healthy, 1),\n",
                "        \"pct_moderate\": round(pct_moderate, 1),\n",
                "        \"pct_unhealthy\": round(pct_unhealthy, 1),\n",
                "        \"mean_ndti\": round(mean_ndti, 4),\n",
                "        \"mean_ndci\": round(mean_ndci, 4),\n",
                "        \"mean_tss\": round(mean_tss, 4),\n",
                "        \"mean_cdom\": round(mean_cdom, 4),\n",
                "        \"status\": status\n",
                "    }"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 7. Eksekusi Pencarian / Pengunduhan Composite Sentinel-2"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "combined_geom = coastal_gdf.union_all()\n",
                "bbox = combined_geom.bounds\n",
                "print(f\"Bbox perairan pesisir Banten: {bbox}\")\n",
                "\n",
                "path_t1 = os.path.join(COMPOSITE_DIR, f\"Banten_Water_{YEAR_T1}.tif\")\n",
                "path_t2 = os.path.join(COMPOSITE_DIR, f\"Banten_Water_{YEAR_T2}.tif\")\n",
                "\n",
                "# Mode download (True = Lewati download, gunakan fallback data lokal yang sudah ada)\n",
                "SKIP_OPENEO = True \n",
                "\n",
                "if not SKIP_OPENEO:\n",
                "    try:\n",
                "        download_banten_composite(connection, bbox, YEAR_T1, path_t1, SCALE_EXPORT)\n",
                "        download_banten_composite(connection, bbox, YEAR_T2, path_t2, SCALE_EXPORT)\n",
                "    except Exception as exc:\n",
                "        print(f\"Error openEO: {exc}. Menggunakan local fallback.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 8. Eksekusi Loop Analisis Kualitas Air per Kecamatan Pesisir Banten"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "final_path_t1 = path_t1 if os.path.exists(path_t1) else os.path.join(COMPOSITE_DIR, f\"Banten_{YEAR_T1}.tif\")\n",
                "final_path_t2 = path_t2 if os.path.exists(path_t2) else os.path.join(COMPOSITE_DIR, f\"Banten_{YEAR_T2}.tif\")\n",
                "\n",
                "print(f\"Menggunakan baseline composite: {final_path_t1}\")\n",
                "print(f\"Menggunakan comparison composite: {final_path_t2}\")\n",
                "\n",
                "ds_t1 = load_composite_as_dataset(final_path_t1)\n",
                "ds_t2 = load_composite_as_dataset(final_path_t2)\n",
                "\n",
                "pixel_area_ha = compute_pixel_area_ha(ds_t2)\n",
                "\n",
                "results = []\n",
                "for i, row in enumerate(coastal_gdf.itertuples()):\n",
                "    name_3 = row.Kecamatan\n",
                "    name_2 = row.Kabupaten_Kota\n",
                "    geom = row.geometry\n",
                "    \n",
                "    print(f\"[{i+1}/{len(coastal_gdf)}] Menganalisis Kecamatan {name_3} ({name_2})...\")\n",
                "    stats_t1 = analyze_kecamatan_water_quality(ds_t1, geom, pixel_area_ha)\n",
                "    stats_t2 = analyze_kecamatan_water_quality(ds_t2, geom, pixel_area_ha)\n",
                "    \n",
                "    if stats_t2 is None:\n",
                "        continue\n",
                "    if stats_t1 is None:\n",
                "        stats_t1 = {\n",
                "            \"water_area_ha\": 0.0, \"healthy_ha\": 0.0, \"moderate_ha\": 0.0, \"unhealthy_ha\": 0.0,\n",
                "            \"pct_healthy\": 0.0, \"pct_moderate\": 0.0, \"pct_unhealthy\": 0.0,\n",
                "            \"mean_ndti\": 0.0, \"mean_ndci\": 0.0, \"mean_tss\": 0.0, \"mean_cdom\": 0.0, \"status\": \"N/A\"\n",
                "        }\n",
                "        \n",
                "    diff_healthy = stats_t2[\"pct_healthy\"] - stats_t1[\"pct_healthy\"]\n",
                "    diff_unhealthy = stats_t2[\"pct_unhealthy\"] - stats_t1[\"pct_unhealthy\"]\n",
                "    \n",
                "    if diff_healthy >= 5.0 and diff_unhealthy <= -5.0:\n",
                "        tren = \"MEMBAIK\"\n",
                "    elif diff_unhealthy >= 5.0:\n",
                "        tren = \"MEMBURUK\"\n",
                "    else:\n",
                "        tren = \"STABIL\"\n",
                "        \n",
                "    results.append({\n",
                "        \"Kabupaten_Kota\": name_2,\n",
                "        \"Kecamatan\": name_3,\n",
                "        \"Luas_Air_2026_Ha\": stats_t2[\"water_area_ha\"],\n",
                "        \"Sehat_2026_Ha\": stats_t2[\"healthy_ha\"],\n",
                "        \"Sedang_2026_Ha\": stats_t2[\"moderate_ha\"],\n",
                "        \"TidakSehat_2026_Ha\": stats_t2[\"unhealthy_ha\"],\n",
                "        \"Pct_Sehat_2026\": stats_t2[\"pct_healthy\"],\n",
                "        \"Pct_Sedang_2026\": stats_t2[\"pct_moderate\"],\n",
                "        \"Pct_TidakSehat_2026\": stats_t2[\"pct_unhealthy\"],\n",
                "        \"Mean_NDTI_2026\": stats_t2[\"mean_ndti\"],\n",
                "        \"Mean_NDCI_2026\": stats_t2[\"mean_ndci\"],\n",
                "        \"Mean_TSS_2026\": stats_t2[\"mean_tss\"],\n",
                "        \"Mean_CDOM_2026\": stats_t2[\"mean_cdom\"],\n",
                "        \"Status_Kualitas_2026\": stats_t2[\"status\"],\n",
                "        \"Luas_Air_2017_Ha\": stats_t1[\"water_area_ha\"],\n",
                "        \"Sehat_2017_Ha\": stats_t1[\"healthy_ha\"],\n",
                "        \"Pct_Sehat_2017\": stats_t1[\"pct_healthy\"],\n",
                "        \"Mean_NDTI_2017\": stats_t1[\"mean_ndti\"],\n",
                "        \"Mean_NDCI_2017\": stats_t1[\"mean_ndci\"],\n",
                "        \"Status_Kualitas_2017\": stats_t1[\"status\"],\n",
                "        \"Delta_Pct_Sehat\": round(diff_healthy, 1),\n",
                "        \"Tren_Kualitas\": tren\n",
                "    })\n",
                "\n",
                "df_results = pd.DataFrame(results)\n",
                "print(f\"\\nAnalisis selesai untuk {len(df_results)} kecamatan.\")\n",
                "df_results.head(10)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 9. Pelatihan Model Machine Learning Global (Random Forest Kualitas Air Banten)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def train_global_rf_model(ds, combined_geom):\n",
                "    print(\"Melatih Model Random Forest Global untuk Kualitas Air Banten...\")\n",
                "    try:\n",
                "        # Potong dengan batas perairan pesisir gabungan seluruh Banten\n",
                "        clipped_ds = ds.rio.clip([combined_geom], crs=\"EPSG:4326\", all_touched=True)\n",
                "    except Exception as e:\n",
                "        print(f\"Error memotong composite global: {e}\")\n",
                "        return None, None\n",
                "        \n",
                "    clipped_ds = calculate_water_quality_indices(clipped_ds)\n",
                "    threshold_classes = classify_water_pixels_threshold(clipped_ds)\n",
                "    water_mask = threshold_classes > 0\n",
                "    features_bands = [\"B02\", \"B03\", \"B04\", \"B08\", \"B11\"]\n",
                "    if \"B05\" in clipped_ds:\n",
                "        features_bands.append(\"B05\")\n",
                "    features_bands.extend([\"NDTI\", \"NDCI\", \"TSS\", \"CDOM\"])\n",
                "    \n",
                "    features_bands = [f for f in features_bands if f in clipped_ds]\n",
                "    print(f\"Fitur: {features_bands}\")\n",
                "    \n",
                "    features_list = [clipped_ds[band].values[water_mask] for band in features_bands]\n",
                "    X = np.stack(features_list, axis=1)\n",
                "    y = threshold_classes[water_mask]\n",
                "    \n",
                "    valid = ~np.isnan(X).any(axis=1)\n",
                "    X = X[valid]\n",
                "    y = y[valid]\n",
                "    \n",
                "    print(f\"Jumlah sampel piksel air global: {len(X)}\")\n",
                "    \n",
                "    from sklearn.model_selection import train_test_split\n",
                "    from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix\n",
                "    \n",
                "    X_train, X_test, y_train, y_test = train_test_split(\n",
                "        X, y, test_size=0.3, random_state=42, stratify=y\n",
                "    )\n",
                "    \n",
                "    rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=5, random_state=42, n_jobs=-1)\n",
                "    rf.fit(X_train, y_train)\n",
                "    \n",
                "    y_pred = rf.predict(X_test)\n",
                "    acc = accuracy_score(y_test, y_pred)\n",
                "    kappa = cohen_kappa_score(y_test, y_pred)\n",
                "    cm = confusion_matrix(y_test, y_pred)\n",
                "    \n",
                "    importances = rf.feature_importances_.tolist()\n",
                "    feat_imp = {band: round(imp, 4) for band, imp in zip(features_bands, importances)}\n",
                "    \n",
                "    print(f\"Akurasi Validasi Model: {acc:.2%}\")\n",
                "    print(f\"Kappa Coefficient: {kappa:.4f}\")\n",
                "    print(f\"Confusion Matrix:\\n{cm}\")\n",
                "    print(f\"Feature Importances:\\n{feat_imp}\")\n",
                "    \n",
                "    metrics = {\n",
                "        \"accuracy\": round(float(acc), 4),\n",
                "        \"kappa\": round(float(kappa), 4),\n",
                "        \"confusion_matrix\": cm.tolist(),\n",
                "        \"feature_importances\": feat_imp,\n",
                "        \"n_train_samples\": int(len(X_train)),\n",
                "        \"n_test_samples\": int(len(X_test)),\n",
                "        \"features_used\": features_bands,\n",
                "        \"trained_at\": datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
                "    }\n",
                "    return rf, metrics\n",
                "\n",
                "rf_model, rf_metrics = train_global_rf_model(ds_t2, combined_geom)\n",
                "\n",
                "if rf_model is not None:\n",
                "    os.makedirs(os.path.join(OUTPUT_DIR, \"model\"), exist_ok=True)\n",
                "    model_path = os.path.join(OUTPUT_DIR, \"model\", \"water_quality_rf.joblib\")\n",
                "    joblib.dump(rf_model, model_path)\n",
                "    print(f\"Model Random Forest global disimpan ke: {model_path}\")\n",
                "    \n",
                "    meta_path = os.path.join(OUTPUT_DIR, \"model\", \"model_metadata.json\")\n",
                "    with open(meta_path, \"w\", encoding=\"utf-8\") as f:\n",
                "        json.dump(rf_metrics, f, indent=2, ensure_ascii=False)\n",
                "    print(f\"Metadata model global disimpan ke: {meta_path}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 10. Ekspor & Pemetaan Hasil Spasial"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Simpan CSV hasil statistik\n",
                "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
                "csv_path = os.path.join(OUTPUT_DIR, \"banten_water_quality_kecamatan.csv\")\n",
                "df_results.to_csv(csv_path, index=False, encoding=\"utf-8-sig\")\n",
                "print(f\"Hasil statistik disimpan ke CSV: {csv_path}\")\n",
                "\n",
                "# Simpan JSON per kecamatan\n",
                "json_path = os.path.join(OUTPUT_DIR, \"banten_water_quality_kecamatan.json\")\n",
                "json_dict = df_results.set_index(\"Kecamatan\").to_dict(orient=\"index\")\n",
                "with open(json_path, \"w\", encoding=\"utf-8\") as f:\n",
                "    json.dump(json_dict, f, indent=2, ensure_ascii=False)\n",
                "print(f\"Hasil statistik disimpan ke JSON: {json_path}\")\n",
                "\n",
                "# Visualisasi Peta Interaktif Folium\n",
                "def create_folium_visualization(coastal_gdf, results_df, output_path):\n",
                "    merged_gdf = coastal_gdf.merge(results_df, on=[\"Kabupaten_Kota\", \"Kecamatan\"], how=\"inner\")\n",
                "    centroid = merged_gdf.union_all().centroid\n",
                "    map_center = [centroid.y, centroid.x]\n",
                "    m = folium.Map(location=map_center, zoom_start=10, tiles=\"cartodbpositron\")\n",
                "    \n",
                "    plugins.Fullscreen(position=\"topright\", title=\"Fullscreen\", title_cancel=\"Exit\").add_to(m)\n",
                "    color_map = {\"SEHAT\": \"#2ecc71\", \"SEDANG\": \"#f1c40f\", \"TIDAK SEHAT\": \"#e74c3c\"}\n",
                "    \n",
                "    # 1. Batas Darat Kecamatan\n",
                "    land_layer = folium.FeatureGroup(name=\"Darat Kecamatan (Administratif)\", show=True)\n",
                "    for idx, row in merged_gdf.iterrows():\n",
                "        folium.GeoJson(\n",
                "            mapping(row[\"land_geom\"]),\n",
                "            style_function=lambda x: {\n",
                "                \"fillColor\": \"#bdc3c7\", \"color\": \"#7f8c8d\", \"weight\": 1.0, \"fillOpacity\": 0.15\n",
                "            },\n",
                "            tooltip=f\"{row['Kecamatan']}, {row['Kabupaten_Kota']}\"\n",
                "        ).add_to(land_layer)\n",
                "    land_layer.add_to(m)\n",
                "    \n",
                "    # 2. Batas Air Pesisir (Warna Hijau/Kuning/Merah)\n",
                "    water_layer = folium.FeatureGroup(name=\"Kualitas Air Pesisir (3 km)\", show=True)\n",
                "    for idx, row in merged_gdf.iterrows():\n",
                "        status = row[\"Status_Kualitas_2026\"]\n",
                "        color = color_map.get(status, \"#7f8c8d\")\n",
                "        tooltip_text = f\"Kecamatan {row['Kecamatan']} ({status})\"\n",
                "        \n",
                "        popup_html = f\"\"\"\n",
                "        <div style='font-family: Arial, sans-serif; font-size: 13px; width: 280px; padding: 5px;'>\n",
                "            <h4 style='margin: 0 0 5px 0; color: #2c3e50;'>Kecamatan {row['Kecamatan']}</h4>\n",
                "            <span style='font-size: 11px; color: #7f8c8d;'>{row['Kabupaten_Kota']}</span>\n",
                "            <hr style='margin: 8px 0;'/>\n",
                "            <b>Luas Zona Air:</b> {row['Luas_Air_2026_Ha']:.1f} Ha<br/>\n",
                "            <b>Status Kualitas (2026):</b> \n",
                "            <span style='color: {color}; font-weight: bold;'>{status}</span><br/>\n",
                "            <b>Perubahan (2017 -> 2026):</b> \n",
                "            <span style='font-weight: bold;'>{row['Tren_Kualitas']}</span><br/>\n",
                "            <hr style='margin: 8px 0;'/>\n",
                "            <table style='width: 100%; font-size: 12px;'>\n",
                "                <tr style='background: #f8f9fa;'>\n",
                "                    <td>🟢 <b>Sehat:</b></td>\n",
                "                    <td style='text-align: right;'>{row['Pct_Sehat_2026']:.1f}% ({row['Sehat_2026_Ha']:.1f} Ha)</td>\n",
                "                </tr>\n",
                "                <tr>\n",
                "                    <td>🟡 <b>Sedang:</b></td>\n",
                "                    <td style='text-align: right;'>{row['Pct_Sedang_2026']:.1f}% ({row['Sedang_2026_Ha']:.1f} Ha)</td>\n",
                "                </tr>\n",
                "                <tr style='background: #f8f9fa;'>\n",
                "                    <td>🔴 <b>Tidak Sehat:</b></td>\n",
                "                    <td style='text-align: right;'>{row['Pct_TidakSehat_2026']:.1f}% ({row['TidakSehat_2026_Ha']:.1f} Ha)</td>\n",
                "                </tr>\n",
                "            </table>\n",
                "        </div>\n",
                "        \"\"\"\n",
                "        folium.GeoJson(\n",
                "            mapping(row[\"geometry\"]),\n",
                "            style_function=lambda x, col=color: {\n",
                "                \"fillColor\": col, \"color\": col, \"weight\": 1.5, \"fillOpacity\": 0.55\n",
                "            },\n",
                "            highlight_function=lambda x, col=color: {\n",
                "                \"fillOpacity\": 0.85, \"weight\": 2.5\n",
                "            },\n",
                "            tooltip=tooltip_text\n",
                "        ).add_child(folium.Popup(popup_html)).add_to(water_layer)\n",
                "    water_layer.add_to(m)\n",
                "    \n",
                "    # Legenda\n",
                "    legend_html = f\"\"\"\n",
                "     <div style=\"position: fixed; \n",
                "                 bottom: 50px; left: 50px; width: 220px; height: 160px; \n",
                "                 border:2px solid grey; z-index:9999; font-size:12px;\n",
                "                 background-color:white;\n",
                "                 opacity: 0.9;\n",
                "                 padding: 10px;\n",
                "                 border-radius: 5px;\n",
                "                 font-family: Arial, sans-serif;\">\n",
                "     <h4 style=\"margin:0 0 8px 0; font-size:13px; color:#2c3e50;\">Kualitas Air Pesisir</h4>\n",
                "     <div style=\"margin-bottom: 5px;\"><i style=\"background:#2ecc71; width:28px; height:12px; float:left; margin-right:8px; opacity:0.7; border-radius: 2px;\"></i>🟢 <b>SEHAT</b> (>50% Sehat)</div>\n",
                "     <div style=\"margin-bottom: 5px;\"><i style=\"background:#f1c40f; width:28px; height:12px; float:left; margin-right:8px; opacity:0.7; border-radius: 2px;\"></i>🟡 <b>SEDANG</b> (Kondisi Sedang)</div>\n",
                "     <div style=\"margin-bottom: 8px;\"><i style=\"background:#e74c3c; width:28px; height:12px; float:left; margin-right:8px; opacity:0.7; border-radius: 2px;\"></i>🔴 <b>TIDAK SEHAT</b> (>30% Unhealthy)</div>\n",
                "     <hr style=\"margin: 5px 0;\"/>\n",
                "     <span style=\"font-size:10px; color:#7f8c8d;\">Banten per Kecamatan (Sentinel-2)</span>\n",
                "     </div>\n",
                "     \"\"\"\n",
                "    m.get_root().html.add_child(folium.Element(legend_html))\n",
                "    folium.LayerControl().add_to(m)\n",
                "    m.save(output_path)\n",
                "    print(f\"Peta interaktif disimpan ke: {output_path}\")\n",
                "    return m\n",
                "\n",
                "html_path = os.path.join(OUTPUT_DIR, \"banten_water_quality_map.html\")\n",
                "map_obj = create_folium_visualization(coastal_gdf, df_results, html_path)\n",
                "map_obj"
            ]
        }
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.2"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    output_path = r"d:\Lombuy IPBuy\Model\Model_Earth.ipynb"
    print(f"Menulis file notebook {output_path}...")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
    print("Notebook berhasil dibuat!")

if __name__ == "__main__":
    main()
